### ISSUE TITLE
Enable code blocks within posts

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#10]
Originally [posted here](https://github.com/cncf/wordpress-site/issues/45).  Try [this plugin](https://melonpan.io/gutenberg-blocks/melonpan-block-code/) by the same author as Post Meta Controls plugin we use.

**Comment by cjyabraham** [comment]
James found [another plugin to consider](https://wordpress.org/plugins/simple-code-block/#description).

**Comment by cjyabraham** [comment]
I reviewed a few options for this and think we should go with [Code Syntax Block](https://wordpress.org/plugins/code-syntax-block/#description).  It extends the native Gutenberg code block.  There are plans to include syntax highlighting in the native code block so, when that is developed, we should be able to just deactivate this plugin and use the built-in syntax highlighting instead.

**Comment by thetwopct** [comment]
Looks good. I noticed the styles and scripts are loaded conditionally when block is present, this does cause a slight problem for old posts as they are not styled (as a newer code block is not present). I have styled the old code snippets via CSS for now so they have a similar / matching style. 

Depending on how many old posts there with code we could load the styles all the time for blog posts using a filter 

`add_filter( 'mkaz_code_syntax_force_loading', '__return_true' );`

Otherwise we could manually go through and convert old posts in to blocks. Unfortunately when converting old blog posts to blocks using the "Convert to Blocks" option, code blocks are turned in to HTML blocks, not code blocks. So this would need to be a manual update.

**Comment by cjyabraham** [comment]
@lucperkins you requested this originally.  [Here it is on our dev site for the CNCF.io rebuild](https://dev-cncfci.pantheonsite.io/2020/04/19/code-block-test/).  Line numbers can be turned on or off.  Does that meet your needs?  If you'd like to play around with it in the admin let me know and I'll get you access.

**Comment by lucperkins** [comment]
@cjyabraham Works for me! Very nice theme, too 🥰

**Comment by cjyabraham** [comment]
I think the immediate scope of this issue is now done.  We can consider improving code block styles of existing posts as a nice-to-have down the road.
