### ISSUE TITLE
Newsletter form field focus styling

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#108]
I'm not sure I like the pink bar on top of the newsletter fields to show focus.  I didn't like it much on lfph.io either.  What about just lighting up the bottom border in pink to show focus?
<img width="1013" alt="Screen Shot 2020-05-30 at 9 39 12 AM" src="https://user-images.githubusercontent.com/463160/83316631-76f86200-a259-11ea-904d-be1ae4d929cb.png">

**Comment by thetwopct** [comment]
The standard :focus is a blue outline around the input, which doesn't look great in this setting. I've removed that, and implemented this custom focus. 
A key accessibility rule is "Color is not used as the only visual means of conveying information" which is why adding an additional border to the input on focus makes sense to me.

**Comment by cjyabraham** [comment]
What about making the focused field have a 2px underline in pink, rather than 1px?  That would meet the accessibility requirement:
<img width="969" alt="Screen Shot 2020-06-04 at 10 49 58 AM" src="https://user-images.githubusercontent.com/463160/83709464-3598f580-a651-11ea-9cb8-21ab7cf1b9a1.png">
