### ISSUE TITLE
make the default image look the same in blog and news listings

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#128]
You can see here that the default image in the news listings has more margin than in the blog listing:
<img width="1088" alt="Screen Shot 2020-06-05 at 3 01 44 PM" src="https://user-images.githubusercontent.com/463160/83846686-930a7080-a73d-11ea-96ae-7d82e3fd8cbf.png">

**Comment by thetwopct** [comment]
Few things here -

- In the News has it's own styling different to the blog
- the in the news logos are constrained by 200px x 200px
- the logos automatically have padding around them (so your logo with padding included adds more padding)
- The height of the images on blog have more height as the content to its right it aligns with is larger
- With all these images, the image isn't being sized, a responsive wrapper is around the image and the image is using object-fit to cover so that it's responsive and adapts to different screen sizes instead of being cut off. This will mean that the space around a logo is not fixed. (View page at 600px to view an obvious example of this).

I've given the default image less padding by default. I am expecting to revisit these logos once Editors start uploading. Other than that, without significant changes to the News page structure, I think this is closed?

**Comment by cjyabraham** [comment]
Sure, let's close for now.  We may receive feedback on these default icons so fine-tuning their presentation right now is likely not worth it.
