### ISSUE TITLE
Make case studies more prominent on cncf.io

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/cncf.io#18]
Currently, we publish the case study and then write a blog.
Julie and I were talking, we don't feel the blog is driving the traffic to the case study.

We'd like to see another way to highlight case studies. Perhaps embedded in text in the site. A banner on the home page for highlighted case study.

Can the case studies have tags so they are automatically pulled into other applicable pages?

... ideas

**Comment by dankohn** [comment]
I would suggest redesigning the end user section of cncf.io to have it take up half the space and use the other half to randomly show 4 of the case studies.

And we could kill "What is CNCF? The Cloud Native Computing Foundation builds sustainable ecosystems and fosters communities to support the growth and health of cloud native open source software." since that section largely duplicates the membership section.

**Comment by cjyabraham** [comment]
@thetwopct is tracking this in his [functional spec](https://docs.google.com/document/d/1rsgfAKWY0MC70ddX0a0eYV91VenG_loT_tS8aoGz0cQ/edit)

**Comment by cjyabraham** [comment]
this is [done](https://dev-cncfci.pantheonsite.io/)
