### ISSUE TITLE
Reconsider when to show the mobile menu

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#211]
Since finding out that Julie is seeing the mobile menu on her Lenovo Thinkpad, we should dig a bit to see what proportion of users would have the same experience.  If it's going to be more than 5% or so, we may want to consider another way of seeing long menus, such as just having them scroll?

**Comment by thetwopct** [comment]
Issue: 

- Mobile menu kicks in at browser sizes either under 1000px wide, or 700px height.
- With small screens + browser bars etc, some browser viewports are only 400-700px high, and the mobile menu is relatively slow to use compared with desktop due to number of options.
- Although we do not have the exact number of users who visit the CNCF site with a small desktop viewport, one of the team members has issues with it, and from a cursory look at Analytics, it does seem that more thab 5% of users could have the issue.

Potential solutions:

1) Use JS - if sub-menu column goes outside screen bottom viewport boundary, apply class to turn sub-menu in to 2 columns. We already have a similar function for the project sub-menus.
Issues: If sub-menu is 2 columns, this reduces space for sub-sub-menu. For instance Sandbox Projects sub-sub-menu is already tight for space in browser. A solution could be to reduce font / spacing on sub-sub-menu if 2 column layout is activated.

2) Deactivate sticky header on browser sizes under 700px. This would allow user to open menu and scroll down to see all items regardless of browser size.
Issue: Inconsistent with mobile / desktop full size

3) Reduce number of items and/or redesign menu
Perhaps adopt a slimmer height wider menu (mega menu style) instead of straight dropdowns.

**Comment by thetwopct** [comment]
I've implemented 2) for now, let me know your thoughts

**Comment by cjyabraham** [comment]
I like it.  Let's see if anyone else can give us a thumbs up in the Slack channel...

**Comment by cjyabraham** [comment]
Should we also do the Meet sub-submenu idea I suggested in Slack?  It would allow us to reduce the screen size cutoff further, so more people keep the sticky topnav.  Meet sub-submenu would be in the Community menu and include:
- Telecom User Group
- Kubernetes Community Days
- Meetups
- Calendar

**Comment by thetwopct** [comment]
I don't have a strong opinion, but I've added it for now to see how you/the team get on with it.

**Comment by cjyabraham** [comment]
Now with the menu change, I think you could unstick the topnav only for browsers less than about 611px tall.  Right now on dev the cut-off seems too tall.

**Comment by thetwopct** [comment]
Stick menu now only applies to screens between 515 and 615px high
