### ISSUE TITLE
Change colour of home page stats background

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#249]
![20200817091733-Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/90373853-7c03cb00-e06a-11ea-9330-e5ad6721235b.jpg)

to

#4472D6

**Comment by cjyabraham** [comment]
Actually, why not use one of these colors rather than using the hello bar color (from [End User Community](https://dev-cncfci.pantheonsite.io/people/end-user-community/)):
<img width="1221" alt="Screen Shot 2020-08-18 at 1 50 35 PM" src="https://user-images.githubusercontent.com/463160/90475451-09721880-e15a-11ea-970d-63310abb0702.png">

The middle blue there is more muted than the hello bar so might be better.

**Comment by thetwopct** [comment]
Updated to the middle blue ✅
