### ISSUE TITLE
Case study template issues

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#260]
- [x] the first block should be 'lf/hero' and not 'core/heading'; I don't know if it's still possible to suggest placeholder text?
- [x] the case study template should be applied to CN case studies in addition to regular ones
- [x] when you start editing a new case study, save it, then reload the page, the 'core/heading' block part-way down the page is always invalid:
<img width="1183" alt="Screen Shot 2020-08-23 at 10 31 42 AM" src="https://user-images.githubusercontent.com/463160/90969494-da79ef00-e52b-11ea-91c0-be09745e3d95.png">

**Comment by thetwopct** [comment]
I've updated the LF MU plugin
1) Added LF/Hero block as the first block
2) Applied to CN case studies (it's the same template, the conditionals should pick up and work the same)
3) Weird one. Turned out to be something very simple.

```
array(
			'core/heading',
			array(
				'level'       => "3",
				'placeholder' => 'Introductory paragraph to the case study',
				'className' => 'is-style-max-width-800',
			),
		),
```

vs

```
array(
			'core/heading',
			array(
				'level'       => 3,
				'placeholder' => 'Introductory paragraph to the case study',
				'className' => 'is-style-max-width-800',
			),
		),
```

Yep, the level 3 needs to be an integer without any quotes....
