### ISSUE TITLE
Not all project logos load in Firefox

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#282]
I reproduced this in FF on both Windows and Mac:
<img width="1106" alt="Screen Shot 2020-08-28 at 8 28 39 PM" src="https://user-images.githubusercontent.com/463160/91560866-259d6300-e96d-11ea-964c-8f3d82f5eaef.png">

It might have something to do with the lazyloading of images?

**Comment by thetwopct** [comment]
It seems it doesn't like this line of CSS:

```
img[src$=".svg"] {
    width: 100%;
    height: auto;
}
```

It can also be fixed by adding width and height dimensions to the SVG file itself.

I've removed the CSS for now, I think I added it originally to help with the Safe SVG / SVG insertion problem when SVGs are very small, please look out for any SVGs that seem deformed now I've removed it.
