### ISSUE TITLE
Homepage hero is blurry

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#309]
The homepage hero uses [this image](https://www.cncf.io/wp-content/uploads/2020/05/welcome-1400x400.jpg) which appears a bit blurry to me.  Can we switch thumbnails to use [this larger version](https://www.cncf.io/wp-content/uploads/2020/05/welcome.jpg)?

**Comment by thetwopct** [comment]
Used image - 1400x400
Suggested image - 1458x517

I'm not sure those 58 pixels hold the difference, more likely to be compression on the image. Wasn't there a way to turn off ShortPixel on certain images from [admin](https://www.cncf.io/wp/wp-admin/upload.php?search=welcome)?

**Comment by thetwopct** [comment]
If we can get the original of that image that would be brilliant - we can then include retina sized image in there. Looking for something at least 2000x580, ideally 2800x800+

**Comment by cjyabraham** [comment]
So, I have actually turned off Shortpixel for that image.  It wasn't gaining us much and made the image look "dirty" and more blurry.  On my screen the suggested image does look a notch sharper and better.  I'll see about getting the original...

**Comment by thetwopct** [comment]
I'm also thinking about the next image / when this hero is updated. What if that is a 5000px x 5000px unsplash photo, using "full" thumbnail then is not advisable. So we should come up with a better solution. Setting a minimum/recommend size that caters for retina devices could be it.

**Comment by cjyabraham** [comment]
Here is [the original image](https://www.flickr.com/photos/143247548@N03/32433210658/in/album-72157704599428714/).  What about using the `hero-2880` thumbnail?

**Comment by thetwopct** [comment]
I've added a new image size that matches the ratio used on the home page. As WP restricts max image size to 2048px, that's the biggest size it will be. [Let me know if this looks better for you](https://dev-cncfci.pantheonsite.io), once deployed I'll upload the new hero image (I aligned it a bit).

**Comment by cjyabraham** [comment]
I have uploaded an image to exactly match those dimensions [to the live site](https://www.cncf.io/) and think it looks a lot better.  I think [your alignment here](https://dev-cncfci.pantheonsite.io/) has moved the central kubernetes logo out of the center, both vertically and horizontally, so I prefer what I've got now on the live site.

**Comment by cjyabraham** [comment]
Interestingly, perhaps because the image I uploaded exactly matches the hero dimensions, I can no longer see FOUC-resizing-thing for the image. 👍

**Comment by cjyabraham** [comment]
The logo on mobile still looks blurry.  Do we need to use a larger thumbnail in that case?
<img width="372" alt="Screen Shot 2020-09-11 at 2 17 18 PM" src="https://user-images.githubusercontent.com/463160/92873392-9185ce00-f439-11ea-8e32-420c553307b3.png">

**Comment by thetwopct** [comment]
On mobile devices, even really old ones, the hero image used is scaled up much higher than it needs to be (due to device pixel ratio) so I'm having trouble solving why it still looks blurry. - example on a 7 year old Nexus 5:
![20200917215208-Dashboard](https://user-images.githubusercontent.com/10615884/93521380-459ec180-f930-11ea-959a-b5e815060f28.jpg)
(See it's using the 1024px x 293px src, for the size of 360x262px, so should be plenty of pixels there). 

I think the best approach would be for me to re-build the block to use the <picture> element instead, in a similar way the hero works. This will work around the srcset/image ratio problem that seems to be preventing other images being used, as above. Closing this in favour of a new issue https://github.com/cncf/cncf.io/issues/329
