### ISSUE TITLE
Blog listing mobile view scrolls horizontally and is too big for the screen

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#328]
[See this page on mobile](https://www.cncf.io/blog/page/5/).  The pagination is wider than the screen so the content can scroll horizontally:
<img width="357" alt="Screen Shot 2020-09-17 at 10 38 55 AM" src="https://user-images.githubusercontent.com/463160/93413558-19ecee80-f8d2-11ea-847c-05e9694dac0c.png">

**Comment by thetwopct** [comment]
From: https://github.com/cncf/cncf.io/pull/330#issuecomment-694699852

```
I think it looks a bit weird having just one page number in the mobile view:
<img width="415" alt="Screen Shot 2020-09-18 at 3 12 13 PM" src="https://user-images.githubusercontent.com/463160/93567554-6400cd80-f9c1-11ea-86a6-d6d8237d6c0c.png">

When you go from desktop to mobile you wonder where the other pages have gone.  If you like it, however, feel free to keep.
```

`When you go from desktop to mobile you wonder where the other pages have gone.`

Users typically don't go from desktop to mobile on one screen. That's what developers of the site do when testing it. 

What is the objective of the pagination? To tell the user the current page and offer a facility to go the next or previous page. Is there another objective I am missing?

If an objective of the development is to make desktop to mobile consistent we have a lot more things to worry about and to redevelop.

Other solutions can be explored, which I currently see as:
- We could wrap the numbers to a new line (this is what I did first, but it didn't look great - the widths of each box is slightly different so they look misaligned)
- Add more page numbers around the current page (but mobile view still won't match desktop due to the crux of the original issue). This may also require a complete rewrite of the `get_the_posts_pagination()` function we are currently using as its options are limited.
- We could change the pagination number to a select box only on mobile (won't match desktop, and seems an excessive form of pagination to meet a next/prev objective) - this would require replacement/rewrite of the `get_the_posts_pagination()` function currently in use.

**Comment by cjyabraham** [comment]
I think we can leave it as you have it.

**Comment by cjyabraham** [comment]
Thinking more about this, I think what's off-putting is that the style of the number is identical to the Next or Prev buttons when you press them.  It makes it look like the number is a pressed button, rather than just informational.  What about removing the border from the number like this:
<img width="256" alt="Screen Shot 2020-09-19 at 1 28 03 PM" src="https://user-images.githubusercontent.com/463160/93659828-03829680-fa7c-11ea-9e4e-6f0a3d55a491.png">

**Comment by thetwopct** [comment]
Not sure I agree that that solution makes more sense.

The links aren't quite following our styling rules, I think this was my original style (v2):

![20200921102211-Category: Blog | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/93745743-52533c00-fbf4-11ea-96d9-71cf09654c12.jpg)

![20200921102318-Category: Blog | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/93745866-83cc0780-fbf4-11ea-96e0-0357e588a16e.jpg)

I think they look a little heavy like this, which is why I switched to the border style instead.

The current page though is the wrong the colour as this is not clickable. Some other styles:

v3) Using grey to denote the current page:

![20200921102706-Category: Blog | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/93746197-0654c700-fbf5-11ea-9c6f-ad91b67ea871.jpg)

v4) Using black border:

![20200921102753-Category: Blog | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/93746263-1d93b480-fbf5-11ea-8fb6-1cbe9f4bd583.jpg)

v5) Using the grey from the skew box:

![20200921103019-Category: Blog | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/93746492-795e3d80-fbf5-11ea-9285-929acf0614b4.jpg)

![20200921103141-Category: Blog | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/93746574-a4e12800-fbf5-11ea-8343-70c3717b8a23.jpg)

I do think it needs some kind of shape around the current page number, otherwise you get this floating effect of a number on its own at the start, and this is the view that the most users will see.

![20200921103331-Category: Blog | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/93746721-e671d300-fbf5-11ea-8ce4-d5636f8211b2.jpg)

**Comment by thetwopct** [comment]
Now there are images on the page, I don't actually mind the heavier style (v2) too much.

If not that one, v5 seems to make the most sense otherwise.

**Comment by cjyabraham** [comment]
I see pros/cons to all the above options... v2 could be worth trying if you're feeling it, otherwise just leave as is?

**Comment by cjyabraham** [comment]
deployed
