### ISSUE TITLE
Editor improvements to be made

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#373]
- Fix automatic PDF style buttons (icon not being added)
- Add "No bottom margin" to H4 and P
- Add 60/40 column layout
- Add a style to remove padding on group (useful on wide align)

**Comment by cjyabraham** [comment]
I'm not sure I understand all the different styles on <p> tags and how they should be used.  Since only one can be selected at once, would the editor often have to choose between controlling the width of a paragraph and controlling its top/bottom margins?  What is the use case for all the margin styles?  And what is "Add Chevrons"?

**Comment by thetwopct** [comment]
> would the editor often have to choose between controlling the width of a paragraph and controlling its top/bottom margins?

Yes as WP only allows for one selection, but so far I haven't seen a situation where more than one is needed.

> What is the use case for all the margin styles?

When a layout requires H/P text to the be close to each other. The TOC of the annual report 2020 is a good example - H tags butted directly up against lists. Having the styles adds no overheads, and gives editors control they previously didn't have.

> And what is "Add Chevrons"?

This is used on the home page and has been in the site design for 6 months. It adds >> after a link.

> where have you applied the no padding on group style? What's the use case?

I haven't applied it anywhere yet. But when editing the AR2020 and home page I felt it could be useful so now it exists.
