### ISSUE TITLE
Create newsletter block to go in sidebar of various pages

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#388]
Include on pages:
- [case study](https://www.cncf.io/case-studies/adform/)
- [Who we are](https://www.cncf.io/about/who-we-are/)
- [webinar](https://www.cncf.io/webinars/cncf-on-demand-webinarrethinking-your-companys-cloud-security-in-the-shadow-of-the-solarwinds-attack/)
- [announcement](https://www.cncf.io/announcements/2021/02/24/cloud-native-computing-foundation-welcomes-47-new-members-at-the-start-of-2021/)
- [event](https://www.cncf.io/events/edge-computing-world/)

<img width="285" alt="Screen Shot 2021-03-03 at 6 07 14 PM" src="https://user-images.githubusercontent.com/463160/109789446-4e1f5600-7c4b-11eb-8986-6c29d1eff9db.png">

**Comment by cjyabraham** [comment]
@Charley-Mann has suggested an edit for the text:
"Get the latest news from the end user community. Subscribe to the CNCF newsletter."

and below the SUBSCRIBE:
"See footer for our robust privacy policy"

@Charley-Mann, I'm noticing that this prompt is specific to end user content while we want to be able to re-use this same newsletter block on various content pages: webinar, announcement, event, etc.  Perhaps they each need their own customized text prompt?  That's more complex to implement but doable.

**Comment by Charley-Mann** [comment]
Ahh - I didn't realise this was for all those page. My apologies! Let me take another pass at that wording.

**Comment by Charley-Mann** [comment]
@cjyabraham  - try this instead. It's much more flexible for various pages on the site and should reflect the #teamcloudnative theme for 2021.

"Get the latest news from our community of doers. Subscribe to the CNCF newsletter."
and below the SUBSCRIBE:
"See footer for our privacy policy"

**Comment by thetwopct** [comment]
I've added the newsletter to the case study singular pages on dev. I've made it so the newsletter box is only added to the page when it doesn't produce too much white space within the case study content.

For the following:

- Who we are
- webinar
- announcement
- events

None of the above pages/posts have sidebars. There is white space, and paragraph content is width restricted so it's easier to read, but none of the pages have sidebars built in. Gutenberg doesn't play particularly nicely with a sidebar layout since sidebars are no longer in vogue (predominantly since Mediums launch in 2012, plus a lot of UX research showing that users ignore sidebars). Case Studies Overview is an outlier as the top content is restricted based on Challenge, Solution, Impact text areas plus the case study data points.

Another consideration is where will the sidebar go on mobile (approx 25% of visitors) if its arranged to go before the content it will appear straight after the hero which isn't a great user experience, if its after the content then it will be next to... the footer subscription form. 

Let me know your thoughts!

**Comment by cjyabraham** [comment]
I agree with your points and like the idea of CTAs at the bottom of content.  I think, however, we should only have them when they are highly relevant to the particular piece of content or else they will just be a distraction and take attention away from the newsletter signup in the footer.  I think we should start small with this and set up analytics to see what kind of impact they are having.  @Charley-Mann, as discussed, let us know when you're ready to start experimenting with these.

**Comment by cjyabraham** [comment]
We have [a new issue for the CTA](https://github.com/cncf/cncf.io/issues/433) so I will close this one.
