### ISSUE TITLE
Consistent of web address for case studies

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/cncf.io#40]
On the current site, the case study page uses "case-studies"
https://www.cncf.io/newsroom/case-studies/

Individual case studies: "case-study"
https://www.cncf.io/case-study/adform_prometheus/

To help with pulling numbers from Google Analytics, can we use the same words - either "case-studies" or "case-study"

**Comment by thetwopct** [comment]
While working earlier I noticed another inconsistency with the URLs

**Announcements category**
https://www.cncf.io/newsroom/announcements/

**Single post in that category** (missing 'newsroom', 'announcement' instead of 'announcements')
https://www.cncf.io/announcement/2020/03/12/cloud-native-computing-foundation-announces-splunk-gold-member/

**Comment by cjyabraham** [comment]
Here's another:
**Speakers Bureau**
https://www.cncf.io/speakers/

**Speaker**
https://www.cncf.io/speaker/puja/

**Comment by cjyabraham** [comment]
@KimMcMahon for now, are you able to just search for "case-stud" in the analytics search?  Does that get you what you need?

**Comment by KimMcMahon** [comment]
There is also the same issue with the China case studies
https://www.cncf.io/newsroom/case-studies-cn/
https://www.cncf.io/case-study-cn/bookingcom/

**Comment by cjyabraham** [comment]
There is some debate on [whether to use singular or plural in folder names](https://serverfault.com/questions/73682/standard-for-singular-vs-plural-type-names-in-urls).  Here is a list of prominent sites that use one or the other:

**Singular**
https://alistapart.com/article/cross-cultural-design/
https://calendar.google.com/calendar/r/month/2020/6/1
https://www.youtube.com/channel/UC3XTzVzaHQEd30rQbuvCtTQ
https://lists.cncf.io/g/newsletter/topic/cncf_newsletter_january_2020/69834710

**Plural**
https://serverfault.com/questions/73682/standard-for-singular-vs-plural-type-names-in-urls
https://stackoverflow.com/questions/6845772/rest-uri-convention-singular-or-plural-name-of-resource-while-creating-it
https://github.com/cncf/cncf.io/issues/39
https://www.facebook.com/groups/cmnomads
https://twitter.com/messages/21658515-22508586
https://jobs.cncf.io/jobs/31901051-engineering-manager-site-reliability-at-wikimedia-foundation

I like the point [this article makes for using plural so that the url is hackable](https://salferrarello.com/singular-vs-plural-wordpress-custom-post-type-permalink/).  With that in mind, I propose the following new url structure for cncf.io:
- https://www.cncf.io/people/end-user-community/ remains as it is
- https://www.cncf.io/events-well-be-at/isc-high-performance-2020/ remains as is
- https://www.cncf.io/webinars/democratizing-analytics-cloud-native-data-warehouses-on-k8s/ remains as is
- https://www.cncf.io/speaker/randy.abernethy/ should change to https://www.cncf.io/speakers/randy.abernethy/
- https://www.cncf.io/announcement/2020/03/12/cloud-native-computing-foundation-announces-splunk-gold-member/ should change to https://www.cncf.io/newsroom/announcements/2020/03/12/cloud-native-computing-foundation-announces-splunk-gold-member/
- https://www.cncf.io/news/2020/03/12/computing-whats-happening-with-serverless-cloud/ should change to https://www.cncf.io/newsroom/in-the-news/2020/03/12/computing-whats-happening-with-serverless-cloud/
- https://www.cncf.io/blog/2020/03/17/how-to-setup-role-based-access-to-kubernetes-cluster/ should change to https://www.cncf.io/newsroom/blog/2020/03/17/how-to-setup-role-based-access-to-kubernetes-cluster/
- https://www.cncf.io/newsroom/case-studies/ should change to https://www.cncf.io/case-studies/
- https://www.cncf.io/case-study/adform/ should change to https://www.cncf.io/case-studies/adform/
- https://www.cncf.io/newsroom/case-studies-cn/ should change to https://www.cncf.io/case-studies-cn/
- https://www.cncf.io/case-study-cn/frameio/ should change to https://www.cncf.io/case-studies-cn/frameio/

URLs I'm not sure about:
- Do we want to change https://www.cncf.io/certification/cka/ to https://www.cncf.io/certifications/cka/?

Any thoughts?
(cc @dankohn )

**Comment by dankohn** [comment]
Plural for consistency is fine with me, with appropriate redirects

**Comment by KimMcMahon** [comment]
Consistency is the most important consideration for me!

**Comment by KimMcMahon** [comment]
@cjyabraham I also have some case studies that are not consistent.
/case-study-adform-prometheus/
/case-study/adform_prometheus/

/case-study/antfinancial/
/case-study/ant-financial/

And there are about 5 more. Is there some instruction we should give Alex going forward to use when she posts the case studies?

**Comment by cjyabraham** [comment]
@KimMcMahon Where do you see /case-study-adform-prometheus/?  It may be an old piece of content.  I believe all the case studies published on the [case studies page](https://www.cncf.io/newsroom/case-studies/) do follow a consistent url structure.  We won't be copying over any of the legacy unpublished case studies to the new site.

**Comment by cjyabraham** [comment]
I have noted all these redirects [in our rebuild plan](https://docs.google.com/spreadsheets/d/1ufJUHCkt4cT_Ovdm3T7y8oRTvj69IEMI9cqJHDYSM6w/edit#gid=1988143597).  I'll close this issue since we'll follow the sheet from here.

**Comment by cjyabraham** [comment]
Reopening because I've run into an issue: it seem that the Speakers Bureau plugin (Ultimate Member) requires a different url for [the directory https://www.cncf.io/speakers/](https://www.cncf.io/speakers/) and the [individual user profiles path https://www.cncf.io/speaker/puja/](https://www.cncf.io/speaker/puja/) so we wouldn't be able to have both on https://www.cncf.io/speakers/.

One alternative I thought of is having the directory at https://www.cncf.io/speakers/search/ so that we can move the speakers profiles to https://www.cncf.io/speakers/puja/.  It's not idea but may be slightly preferable.  Any thoughts?

**Comment by cjyabraham** [comment]
Actually, cancel that, that idea doesn't work either with the way UM routes paths... I recommend we just stay with what we have for now even though it won't be perfectly consistent with the way we'll use plurals on other parts of the site.  Feel free to reopen if you disagree.
