### ISSUE TITLE
LF Stats block redesign

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#569]
I think it would look better if the stats block keeps within the standard 900px content width for project journey reports: https://www.cncf.io/reports/vitess-project-journey-report/

**Comment by thetwopct** [comment]
This block was originally created for our About Us page, but its now not used there and is instead being used only for reports , but: 
- Reports use a lot longer numbers than we originally designed this for (e.g. ">17,000" rather than "116")
- Reports typically have more than 5 big stats they want to promote

Considering on the etcd report the numbers are already squeezed at 1200px wide, we could probably do with looking at the design / layout. The numbers could perhaps be in a 2x3 layout and that would give them more space in 900px layout. Do you want to get some design input on this?

**Comment by cjyabraham** [comment]
I've asked G to suggest a design here

**Comment by cjyabraham** [comment]
Design [from figma](https://www.figma.com/file/utZy1o7ptQdHAO9qOzgzi3/Basic-Report-Styling?node-id=0%3A1):
<img width="1128" alt="Screen Shot 2022-07-08 at 7 12 40 PM" src="https://user-images.githubusercontent.com/463160/177990065-2edd61f1-aff9-475f-9de0-e5b15acdaf37.png">

**Comment by thetwopct** [comment]
- The line like that are not really reminiscent of any other design pattern on the site and the 6th empty box looks strange to me
- Can we get a quick mockup for mobile? As I am not sure how the vertical lines should contract/grow with the screen
- I notice this doesn't meet your requirement for originally opening the ticket (it goes outside the 900px width)
- Could we try some different datasets to see how it looks? That way the block would be more useful to more than just project journey reports.

![2022-08-18-164452@2x](https://user-images.githubusercontent.com/10615884/185365081-b8d4b2bd-dbf9-4332-b180-abaecca478ea.jpg)

![2022-08-18-163906@2x](https://user-images.githubusercontent.com/10615884/185363887-c1cf59fb-c6bd-4382-aeff-ef63e420ba15.jpg)

![2022-08-18-164126@2x](https://user-images.githubusercontent.com/10615884/185364310-c32f19fa-85f2-494e-b9b7-adb9d37952ed.jpg)

![2022-08-18-164210@2x](https://user-images.githubusercontent.com/10615884/185364443-9a651b8a-d5a7-4250-8edb-583bbbc4681a.jpg)

![2022-08-18-163834@2x](https://user-images.githubusercontent.com/10615884/185363795-6c301342-674c-4ddc-b6d9-5e05d3e2b36a.jpg)

**Comment by cjyabraham** [comment]
Let's hold on this for now. With the upcoming Project Journey reports, let's see what designs they come up with to judge whether this issue is still relevant or whether we need to implement some new approach.

**Comment by cjyabraham** [comment]
sounds like we're opting for a full redesign of Project Journey reports so I'll close this much more limited issue
