### ISSUE TITLE
Hello bar shown above mobile menu

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#627]
When the hello bar is activated and you open the mobile menu at the top of a page, the hello menu peaks out at the top. Of course, this is only relevant if the hello bar actually gets used.
<img width="374" alt="Screen Shot 2022-12-02 at 12 00 58 PM" src="https://user-images.githubusercontent.com/463160/205376159-1244481f-1859-4fe6-a05c-32c7456e5cde.png">

**Comment by thetwopct** [comment]
I've updated the code for this - the hello bar is now hidden when the mobile menu is open. This causes a slight move of the close button when at the top of the page. The most elegant solution would be to make the mobile menu open under the hello bar, but because of the way the nav and hello bar is made, and the hello bar is a variable height, it would require some JS to make sure it opens in the right place. For now, and considering Hello Bar is rarely used, I think this is fine.

https://user-images.githubusercontent.com/10615884/215956018-03eb6cd0-29cd-4e4d-8d2d-b3bf43fb79f2.mp4
