### ISSUE TITLE
Move byline up to dateline on blog posts

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#74]
I think the byline, when it exists, could go next to the dateline on [blog posts](https://dev-cncfci.pantheonsite.io/blog/2020/04/28/a-complete-storage-guide-for-your-kubernetes-storage-problems/) to make things a bit more compact:
<img width="590" alt="Screen Shot 2020-05-11 at 11 17 12 AM" src="https://user-images.githubusercontent.com/463160/81521231-29cf5180-9379-11ea-9af8-80ff2d8f32a7.png">

**Comment by thetwopct** [comment]
Would rather come back to this once we know what we're doing regarding Guest Author block.

**Comment by thetwopct** [comment]
Had a play with this - skew box and normal paragraph text doesn't look brilliant on same line. I feel like we will need to revisit the blog post styling - maybe something I can get Luke to look at to give it some styling. Maybe the single posts deserve the hero image layout rather than this plainer approach.

**Comment by cjyabraham** [comment]
I wasn't suggesting the skew box and normal text be on the same line.  I was thinking that the date and author be on the same line.  Did you try that?
