### ISSUE TITLE
People profiles have a lot of whitespace on tablet widths

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#761]
from iPad 10 with Safari

<img width="393" alt="Screen Shot 2023-07-16 at 9 04 42 AM" src="https://github.com/cncf/cncf.io/assets/463160/8fa4ac98-0df9-404f-b741-8be07b114858">

**Comment by thetwopct** [comment]
The height is the same for any device over 768px. 
We based the max height of the modal to roughly fit the longest profiles - 800px height. 
In this example the person has a short-ish profile.
With a long profile on iPad, I would say it looks good:

<img width="478" alt="Screenshot-2023-08-25 --11 13 31@2x" src="https://github.com/cncf/cncf.io/assets/10615884/2407de5c-1c31-4b49-8704-8838ad7d68b6">

Setting a max height results in all modals opening in the same place on the screen. I can apply "fit-content" to the max-height, but then the profiles jump around the screen depending on the length of the profile - I don't think this looks good.

![Screenshot-2023-08-25 --11 11 44](https://github.com/cncf/cncf.io/assets/10615884/eb3ed7d1-601b-4a50-8f6d-fa6fdd2d2a4c)

Solutions:
- Proceed with all the modals loading at different sizes using fit-content. Looks bad IMO.
- Reduce the max height to say 700px instead of 800px - this would make the example above have slightly less white space but should still work, and would reduce the white space a little for your example. Doesn't really solve the issue though. Reducing to 600px clips off too many profiles.
- Setup differing modal ambassadors height and a staff height - staff typically have shorter profiles (would need to double check on this)

Overall, I would see this as an edge case and as majority of cases it works, I'd suggest this to be a Won't Fix.
