### ISSUE TITLE
Projects accepted over time chart seems incorrect

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#767]
The chart reports 20 graduated projects, but currently there are 22

<img width="1251" alt="Screenshot-2023-07-27 --15 40 26@2x" src="https://github.com/cncf/cncf.io/assets/10615884/8442a324-db5c-45f9-b766-57a3d3472c2e">

I can see the chart cut-off date is 1st July, and 2 projects graduated this month - so maybe the chart ignores the current date? If its possible to make it run until today think that would be nicer and more accurate.

**Comment by cjyabraham** [comment]
I changed it to plot the final point marked as the current day. It's not quite perfect because the horizontal spacing of this final point is the regular month spacing, however, at least it now shows all projects up to the current day on the chart. 

FYI I couldn't find a way to style that final segment in a lighter shade to show that the month was still in progress. It would be such a small segment anyway that I'm not sure that method of styling would be effective.
