### ISSUE TITLE
Create a hidden Ambassador calendar page 

### ISSUE THREAD

**Issue by k8tgreenley** [cncf/cncf.io#812]
I would like to create a hidden ambassador calendar page that I can share the link with ambassadors. The page would be set up similar to the https://www.cncf.io/calendar/ page but would be embedded with this calendar: https://tockify.com/cncfamb/monthly

Embedded code:
[tockify component="calendar" calendar="cncfamb"]

Embedded code for submit an event code:
<a href="https://tockify.com/tkf2/submitEvent/fe58cba8fa414e9895dcbdef2f47f7c1" target="_blank">Submit an Event</a>

**Comment by kumarankit999** [comment]
That would be a great Idea for Ambassadors!

**Comment by thetwopct** [comment]
@k8tgreenley 

Here's a preview - https://www.cncf.io/?page_id=97765&preview=1&_ppp=509ef51c1f
Is that what you were looking for?
Once live, it could live at the following URL
https://www.cncf.io/people/ambassadors/calendar/
Let me know any changes

**Comment by k8tgreenley** [comment]
@thetwopct this is precisely what I am looking for! Is it possible to have the submission form open in a new window?

Otherwise this is approved to move forward :)

**Comment by cjyabraham** [comment]
It’s possible, however, we no longer use that convention on any links on the site in order to improve accessibility.

The practice is not recommended for a few reasons:

- It can be disorienting to screen reader users, those with cognitive impairments or people who magnify their screen
- In a lot of cases it actually makes it harder to go back to the page you left since the Back button won’t take you there. This affects all users and is exacerbated on mobile where the old window is never visible.
- Opening a new tab takes control out of the user’s hands

[See this article for a full analysis](https://www.nngroup.com/articles/new-browser-windows-and-tabs/).

**Comment by cjyabraham** [comment]
The page is now live: https://www.cncf.io/people/ambassadors/calendar/

Let us know if you need any other tweaks.
