### ISSUE TITLE
Style Spotlights

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#82]
Style the following:
- [x] [individual spotlight pages](https://dev-cncfci.pantheonsite.io/spotlights/etcd/); no need for an author byline
- [x] [search results](https://dev-cncfci.pantheonsite.io/spotlights/); feel free to refactor the markup etc.
- [x] Create widget on homepage that pulls in the latest 3 spotlights and basically replicates the content and style of what's currently on the [cncf homepage](https://www.cncf.io/)

**Comment by thetwopct** [comment]
How do you want to handle the descriptive text currently used only on the home page?

 i.e. "The incubating project recently completed a security audit with Jepsen." 

I am expecting this text to also be used on the search results page longer term, rather than just set in home page block.

Currently, I have set it up as excerpt for now, but as this defaults to content when not set and length can get unwieldy, it may be better to set up a meta field for this text?

**Comment by cjyabraham** [comment]
[I've added a subtitle meta value](https://github.com/cncf/cncf.io/commit/94aeaecbcd7bcf18d9f72fc7b6ede72739c7c542).  Does that [work](https://dev-cncfci.pantheonsite.io/spotlights/)?

**Comment by cjyabraham** [comment]
FWIW, I feel the linked title in [the results](https://dev-cncfci.pantheonsite.io/spotlights/) needs to be a bit bigger to stand out above the date and type.

**Comment by cjyabraham** [comment]
This is done
