### ISSUE TITLE
Improve our security score

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#842]
Let's improve [this security score](https://observatory.mozilla.org/analyze/www.cncf.io) which currently gives us an F.

**Comment by thetwopct** [comment]
I have issues getting that report to load
I found a couple of alternatives, but there may also be others worth exploring:
https://www.hardenize.com/report/cncf.io/1713670549
https://www.immuniweb.com/websec/www.cncf.io/RT6VmvDP/

Missing:

1) HSTS Preloaded

I ran the CNCF website through this checker
https://hstspreload.org/?domain=www.cncf.io 
https://hstspreload.org/?domain=cncf.io

2) Content Security Policy

Imparting a stricter control on what can embedded / included on our site. This could cause problems with the CNCF blog, which currently embeds content from many sources. But the blog is also where our site could be exploited, so some control could be good. We would need to discuss this and weight up the potential extra work involved.

This plugin seems to be recommended a lot for WP - https://wordpress.org/plugins/gd-security-headers/

For monitoring CSP, https://report-uri.com (to hand off reporting and alerts)

3) DMARC

We would need to generate the DMARC DNS record, add it to our DNS (I think through https://dnsimple.com) and monitor it.

Reporting could be fed back to https://report-uri.com

### Overall

From [reading](https://blog.diogomonica.com/2015/12/29/from-double-f-to-double-a/) around, CSP is a large part of the security score, but this could also cause us the most problems with content. Let's discuss next steps on our call.

**Comment by thetwopct** [comment]
I've pushed up some changes for this to #904 PR

This improves our score to B-

![Image](https://github.com/user-attachments/assets/32714da7-e376-4946-b720-f932616058ff)

- CSP - this is hard for us to implement due to the blogs nature of embedding 3rd party images, code examples and videos
- Subresource Integrity - I don't think this is possible as some our 3rd party scripts don't support this
- X-Content-Type-Options - related to above, trying to implement this may break 3rd party scripts

I think this is as far as we can reasonably take it

**Comment by cjyabraham** [comment]
Looks good. Thanks.

I've [copied these updates over to the Presentations site](https://github.com/cncf/presentations-website/pull/17/commits/7744a45d321dec3abc3beb2f9df11e5cad051699).
