### ISSUE TITLE
Gravity Forms improvements

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#90]
1) It would provide a nicer experience for users to enable AJAX submission on all Gravity Forms used (SB Singular + Bulk) so the page does not refresh on submit.

Can be done via the shortcode. 

`[gravityform id="1" description="false" ajax="true"]`

2) For the Bulk Email form, suggest we set Field Size: Large so form fields fill the width. Needs to be done per input under Appearance tab.

**Comment by cjyabraham** [comment]
1. Done.  Can you reposition the spinner on the [singular form](https://dev-cncfci.pantheonsite.io/speaker/puja/).  It looks fine already on the bulk form.
<img width="805" alt="Screen Shot 2020-05-17 at 9 28 13 AM" src="https://user-images.githubusercontent.com/463160/82133623-f3824e00-9820-11ea-9e89-66b0f210f09d.png">

2. Done.

**Comment by cjyabraham** [comment]
1. It turns out when we turn on the ajax for the [individual speaker contact form](https://dev-cncfci.pantheonsite.io/speaker/cabraham/) it breaks the profile update form submission process.  So I've turned off ajax on it for now.  I'll re-assign to myself and mark "nice-to-have" as I don't think it's essential to have ajax for this form but would be nice.

**Comment by cjyabraham** [comment]
SB is shutdown
